[package]
name = "rune-modules"
version = "0.10.3"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/rune-rs/rune"
homepage = "https://github.com/rune-rs/rune"
documentation = "https://docs.rs/rune-modules"
keywords = ["language", "scripting"]
categories = []
description = """
Native modules for Rune, an embeddable dynamic programming language for Rust.
"""

[features]
default = ["test", "core", "io", "fmt", "macros", "disable-io"]
full = ["time", "http", "json", "toml", "fs", "process", "signal", "rand", "io", "fmt", "macros"]
time = ["tokio", "tokio/time"]
fs = ["tokio", "tokio/fs"]
http = ["reqwest"]
json = ["serde_json"]
process = ["tokio/process"]
signal = ["tokio/signal"]
rand = ["nanorand"]
experiments = []
capture-io = ["parking_lot"]
disable-io = []
test = []
core = []
io = []
fmt = []
macros = []
wasm-bindgen = ["parking_lot/wasm-bindgen"]

[dependencies]
reqwest = { version = "0.11.6", optional = true, default-features = false, features = ["rustls-tls", "gzip", "json"] }
tokio = { version = "1.14.0", optional = true }
serde_json = { version = "1.0.72", optional = true }
toml = { version = "0.5.8", optional = true }
nanorand = { version = "0.6.1", optional = true, features = ["getrandom"] }
parking_lot = { version = "0.11.2", optional = true }

rune = {version = "0.10.3", path = "../rune"}

[package.metadata.docs.rs]
all-features = true
