[workspace]
members = [
    "crates/runestick",
    "crates/runestick-macros",
    "crates/rune-modules",
    "crates/rune-macros",
    "crates/rune-testing",
    "crates/rune",
    "crates/rune-cli",
]