[workspace]
members = [
    "crates/rune",
    "crates/rune-cli",
    "crates/rune-ssa",
    "crates/rune-languageserver",
    "crates/rune-macros",
    "crates/rune-modules",
    "crates/rune-wasm",
    "crates/runestick",
    "crates/runestick-macros",
    "tests",
    "examples",
    "benches",
]

exclude = [
    "tools/builder",
    "tools/site",
    "tools/generate",
]

[profile.bench]
lto = false
debug = true
