[package]
name = "rune-macros"
version = "0.12.1"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2021"
rust-version = "1.63"
readme = "README.md"
repository = "https://github.com/rune-rs/rune"
homepage = "https://github.com/rune-rs/rune"
documentation = "https://docs.rs/rune"
keywords = ["language", "scripting"]
categories = []
description = """
Helper macros for Rune.
"""

[dependencies]
syn = { version = "1.0.82", features = ["full"] }
quote = "1.0.10"
proc-macro2 = { version = "1.0.32", features = ["span-locations"] }

[dev-dependencies]
rune = {version = "0.12.1", path = "../rune"}

[lib]
proc-macro = true
path = "src/lib.rs"
