[package]
name = "rune-macros"
version = "0.6.16"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/rune-rs/rune"
homepage = "https://github.com/rune-rs/rune"
documentation = "https://docs.rs/rune-modules"
keywords = ["language", "scripting"]
categories = []
description = """
Native macros for Rune.
"""

[dependencies]
rune = {version = "0.6.16", path = "../rune"}
runestick = {version = "0.6.16", path = "../runestick"}

[package.metadata.docs.rs]
all-features = true
