[package]
name = "generate"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0.116", features = ["derive"] }
serde_yaml = "0.8.13" 
genco = "0.15.0"
anyhow = "1.0.32"
