[package]
name = "rune-languageserver"
version = "0.10.1"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/rune-rs/rune"
homepage = "https://github.com/rune-rs/rune"
documentation = "https://docs.rs/rune-languageserver"
keywords = ["language", "scripting"]
categories = []
description = """
Language server for Rune.
"""

[dependencies]
tokio = { version = "1.14.0", features = ["full"] }
tokio-util = { version = "0.6.9", features = ["codec"] }
lsp = { version = "0.91.1", package = "lsp-types" }
futures-core = "0.3.0"
anyhow = "1.0.49"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
hashbrown = "0.11.2"
log = "0.4.14"
log4rs = "1.0.0"
ropey = "1.3.1"

rune = {version = "0.10.1", path = "../rune"}
rune-modules = {version = "0.10.1", path = "../rune-modules", features = ["full", "experiments"]}

[build-dependencies]
anyhow = "1.0.49"
