[package]
name = "rune-languageserver"
version = "0.12.1"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2021"
rust-version = "1.63"
readme = "README.md"
repository = "https://github.com/rune-rs/rune"
homepage = "https://github.com/rune-rs/rune"
documentation = "https://docs.rs/rune-languageserver"
keywords = ["language", "scripting"]
categories = []
description = """
Language server for Rune.
"""

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
tokio-util = { version = "0.7.3", features = ["codec"] }
lsp = { version = "0.93.0", package = "lsp-types" }
futures-core = "0.3.21"
anyhow = "1.0.60"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
hashbrown = "0.12.3"
tracing = "0.1.36"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.15"
ropey = "1.5.0"

rune = {version = "0.12.1", path = "../rune"}
rune-modules = {version = "0.12.1", path = "../rune-modules", features = ["full", "experiments"]}

[build-dependencies]
anyhow = "1.0.60"
