[package]
name = "runestick"
version = "0.5.1"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/rune-rs/rune"
homepage = "https://github.com/rune-rs/rune"
documentation = "https://docs.rs/runestick"
keywords = ["language", "scripting"]
categories = []
description = """
Runescript, a generic stack-based virtual machine for Rust.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
twox-hash = "1.5.0"
thiserror = "1.0.20"
hashbrown = "0.8.1"
serde = "1.0.114"
itoa = "0.4.6"
ryu = "1.0"
futures = "0.3.5"
# used to store errors raised in user-defined functions.
anyhow = "1.0.32"
pin-project = "0.4.23"

[dev-dependencies]
tokio = {version = "0.2.22", features = ["full"]}
checkers = "0.5.6"